### ISSUE TITLE
Problems accessing to the SITMUN3 database in the 'persistence-1' Docker container

### ISSUE THREAD

**Issue by RicardCots** [sitmun/sitmun-application-stack#10]
**Describe the bug**
It shows the following error (see attached screenshot) when trying to connect to the Postgres SITMUN3 database in the container.

**To Replay
Steps to reproduce the behaviour:
1. 1. Install/Open dbeaver 2.
2. Try to configure the connection
3. Attempt to connect

**Expected behaviour
To be able to connect to the SITMUN3 postgis database.

**Screenshots**
![image](https://github.com/user-attachments/assets/07c3b311-f042-4572-8500-524bee1fcc7c)

**Desktop (please complete the following information):**
 - OS: Windous
 - DBeaver 24.1.3

**Comment by SoldierFace** [comment]
try this
https://bit.ly/4evXrQ6

you may need to install the c compiler

**Comment by fjlopez** [comment]
The connection works with:

- DBeaver version 24.2.0
- Host: localhost (aslo tested with a DHCP IP 155.210.XXX.XXX)
- Port: 9003
- Database: sitmun3
- Authentication: Database Native
- Username: sitmun3
- Password: sitmun3
- Local Client: <not present>

I observed that DBeaver is running in a machine with IP 10.1.100.161 (see top of the screenshot). Is DBeaver running on the same machine than Docker?

**Comment by RicardCots** [comment]
Finally connected!!

![imagen](https://github.com/user-attachments/assets/277aa3cd-6b20-4f7d-94fd-9a65116a7132)

I've have had to use a diferent Database type. Using 'PostreSQL (Old)' insteed the 'PostgreSQL' that I was using before.

![imagen](https://github.com/user-attachments/assets/22d4fc63-408f-4bff-adc8-ff3d45fc9415)
