### ISSUE TITLE
Error con nuevas instalaciones del Sitmun Application Stack

### ISSUE THREAD

**Issue by albertcoro** [sitmun/sitmun-application-stack#6]
En instalacions desde 0 del Sitmun Application Stack, sale un error durante la ejecuccion del comando:
`docker compose up`

Como recrear error:

- Clonar el proyecto (git clone --recurse-submodules https://github.com/sitmun/sitmun-application-stack.git)
- Acceder al proyecto (cd sitmun-application-stack)
- Añadir el token de github (al .env)
- Ejecutar docker compose up en terminal

Es un error nuevo ya que cuando el proyecto esta cacheado anteriormente funciona perfectamente, pero si pones
el flag de --no-cache no funciona.

Error:
Initialized native services in: /root/.gradle/native Initialized jansi services in: /root/.gradle/native To honour the JVM settings for this build a single-use Daemon process will be forked. See
https://docs.gradle.org/7.4/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Starting process 'Gradle build daemon'. Working directory: /root/.gradle/daemon/7.4 Command: /usr/local/openjdk-11/bin/java --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.prefs/java.util.prefs=ALL-UNNAMED --add-opens java.base/java.nio.charset=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.util.concurrent.atomic=ALL-UNNAMED -Xmx2560m -Dfile.encoding=UTF-8 -Duser.country -Duser.language=en -Duser.variant -cp /root/.gradle/wrapper/dists/gradle-7.4-bin/c0gwcg53nkjbqw7r0h0umtfvt/gradle-7.4/lib/gradle-launcher-7.4.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 7.4 Successfully started process 'Gradle build daemon' An attempt to start the daemon took 1.418 secs. The client will now receive all logging from the daemon (pid: 39). The daemon log file: /root/.gradle/daemon/7.4/daemon-39.out.log Closing daemon's stdin at end of input. The daemon will no longer process any standard input. Daemon will be stopped at the end of the build Using 8 worker leases. Watching the file system is configured to be enabled if available Unable to list file systems to check whether they can be watched. Disabling watching. Reason: Could not query file systems: could not open mount file (errno 2: No such file or directory) File system watching is inactive Starting Build Settings evaluated using settings file '/usr/src/sitmun-backend-core/settings.gradle'. Projects loaded. Root project using build file '/usr/src/sitmun-backend-core/build.gradle'. Included projects: [root project 'sitmun-backend-core', project ':cli', project ':common', project ':deploy', project ':legacy', project ':deploy:heroku-dev-full', project ':deploy:heroku-dev-lite', project ':deploy:preprod'] > Configure project : Evaluating root project 'sitmun-backend-core' using build file '/usr/src/sitmun-backend-core/build.gradle'. Resource missing. [HTTP GET:
https://repo.maven.apache.org/maven2/org/ajoberstar/grgit/grgit-core/4.0.0/grgit-core-4.0.0.pom]
Resource missing. [HTTP GET:
https://repo.maven.apache.org/maven2/khttp/khttp/1.0.0/khttp-1.0.0.pom]
FAILURE:Build failed with an exception. * What went wrong: A problem occurred configuring root project 'sitmun-backend-core'. >Could not resolve all files for configuration ':classpath'. > Could not find org.ajoberstar.grgit:grgit-core:4.0.0. Searched in the following locations: -
https://plugins.gradle.org/m2/org/ajoberstar/grgit/grgit-core/4.0.0/grgit-core-4.0.0.pom
If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration. Required by: project : > org.ajoberstar.git-publish:org.ajoberstar.git-publish.gradle.plugin:2.1.3 > org.ajoberstar:gradle-git-publish:2.1.3 > Could not find khttp:khttp:1.0.0. Searched in the following locations: -
https://plugins.gradle.org/m2/khttp/khttp/1.0.0/khttp-1.0.0.pom
If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration. Required by: project : > org.springdoc.openapi-gradle-plugin:org.springdoc.openapi-gradle-plugin.gradle.plugin:1.3.0 > org.springdoc:springdoc-openapi-gradle-plugin:1.3.0 * Try: >Run with --stacktrace option to get the stack trace. > Run with --debugoption to get more log output. >Run with--scan to get full insights. * Get more help at
https://help.gradle.org/
BUILD FAILED in 9s

**Comment by fjlopez** [comment]
Fixed

**Comment by fjlopez** [comment]
El fallo tenía que ver con problemas externos en los repositorios Maven. Se han actualizado dos plugins en sitmun-backend-core para resolver el problema con sus dependencias. De paso se ha corregido un error detectado en la carga de datos de prueba.

**Comment by fjlopez** [comment]
@albertcoro, tu docker build no ha detectado el cambio en el submódulo y está haciendo el build usando la cache. Observa que en tu mensaje de log los plugins `org.ajoberstar.git-publish` y `org.springdoc.openapi-gradle-plugin` tienen respectivamente las versiones `2.1.3` y `1.3.0`. El patch que he subido las ha actualizado a las versiones `3.0.1` y `1.5.0`. Puedes ver que efectivamente son estas versiones en `sitmun-application-stack/back/backend/sitmun-backend-core/gradle.build`. Si no lo son, es que no has clonado o sincronizado el repositorio correctamente.

Ejecuta `docker compose build --no-cache` para que invalide las caches y use el fichero `gradle.build` actualizado.

**Comment by fjlopez** [comment]
Actualizada la rama `feature-4` también. Además se ha actualizado a los últimos cambios vuestros, por lo que el dockerfile del front se ha actualizado para usar solo node 18.
