### ISSUE TITLE
Error 404 en request "/backend/api/dashboard/info"

### ISSUE THREAD

**Issue by albertcoro** [sitmun/sitmun-application-stack#7]
La request de "/backend/api/dashboard/info" devuelve un error 404. 

Como recrear el error:
- Ejecutar `docker compose up` en terminal
- Abrir en el navegador el dashboard [http://localhost:9000/admin/#/dashboard](url)
- En las "Herramientas de Desarrolladores"/"Red" se puede ver el error

Headers Request:
 -   Request URL: http://localhost:9000/backend/api/dashboard/info
 -   Request Method: GET
 -   Status Code: 404 Not Found
 -   Remote Address: [::1]:9000
 -   Referrer Policy: strict-origin-when-cross-origin

Respuesta Request:
{
    "timestamp" : "2024-07-24T07:47:10.127+00:00",
    "status" : 404,
    "error" : "Not Found",
    "message" : "",
    "path" : "/api/dashboard/info"
}

**Comment by fjlopez** [comment]
Resuelto. Revisa tu ultimo merge de la aplicación de administración. La aplicación no llega a arrancar. 

https://github.com/sitmun/sitmun-admin-app/commit/3144d2dbd0a83f29f6b7223a31b130ea82834582

Si ves necesario que cree un issue para que lo puedas reproducir, avísame.
